spring:
  application:
    name: super-ai-agent

  datasource:
    url: jdbc:postgresql://rm-cn-2zm494skw000htko.rwlb.rds.aliyuncs.com:5432/super_ai_agent
    username: super_ai_agent
    password: Sunjia12500

  ai:
    dashscope:
      api-key: sk-effdc91db4234d1aa416e3d633a95d77
      chat:
        options:
          model: qwen-plus

    vectorstore:
      pgvector:
        index-type: hnsw
        dimensions: 1536
        distance-type: cosine_distance
        max-document-batch-size: 10000

  ollama:
    base-url: http://localhost:11434/
    chat:
      model: deepseek-r1:1.5b

server:
  port: 8089
  servlet:
    context-path: /ai




super-ai-agent:
  baseUrl: https://dashscope.aliyuncs.com/compatible-mode/v1
  sdk:
    apiKey: sk-effdc91db4234d1aa416e3d633a95d77

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug