spring:
  application:
    name: mcp-server-weather
  profiles:
    active: stdio
server:
  port: 8127

gaode:
  weather:
    api_key: 19474fc1c3b0e544b30d0227291f78a4
    request_url: https://restapi.amap.com/v3/weather/weatherInfo?